### ISSUE TITLE
Border polygon for Poland needs to be more exact

### ISSUE THREAD

**Issue by ppawel** [ppawel/osmonitor#19]
See DW472 for example - there are parts in Czech Republic.

**Comment by SunCobalt** [comment]
http://boundaries.osm4people.org/poland.kml

It is the country border. Can also provide land mass border but should not make much difference as long as there are no roads at the sea

Derived from OpenStreetMap Border Polygon converted with QGIS

**Comment by antblant** [comment]
The same with http://geowebhost.pl/osmonitor/browse/road/PL/DK35

**Comment by ppawel** [comment]
Borders provided by Thomas solved the problem.
