### ISSUE TITLE
relation has wrong network=* value (is srb:national, should be srb:motorways)

### ISSUE THREAD

**Issue by SunCobalt** [ppawel/osmonitor#24]
Serbia has no route ref for motorways. They currently have Mxx and Rxxx roads. A M raod road can go over motorways, trunks etc although it is most of the time primary -> M must be at minimum primary or above (trunk, motorway). Same applies to R roads in theory...but same here, a R road should be secondary or higher

**Comment by ppawel** [comment]
This message is only about the "network" tag - for example in Poland there is a convention for this tag depending on road type, also see:

https://wiki.openstreetmap.org/wiki/Relation:route#Road_routes

If there is no such convention for Serbia, this validation can be skipped by OSMonitor.

**Comment by ppawel** [comment]
Let me know what is the convention in Serbia (or if there is one) - I will adjust the configuration.

**Comment by SunCobalt** [comment]
M roads are national roads. Motorways and expressways have no own numbering shema. M roads should be recognised as network=RS:national and R roads as network=RS:regional.

**Comment by ppawel** [comment]
Corrected the configuration.
