### ISSUE TITLE
Length calulcation does not work always (loop)

### ISSUE THREAD

**Issue by SunCobalt** [ppawel/osmonitor#26]
as discussed, not sure where to start to explain it

**Comment by ppawel** [comment]
This is a complex issue to explain, I have some ideas how to improve the implementation but for now I need to provide more documentation with pictures and examples.

**Comment by ppawel** [comment]
Introduced new heuristics and also multiple different algorithms are tried for all roads so it should work proprely on more roads now. Please create new issues for specific roads that have problems.
