### ISSUE TITLE
Broken link for road with no relation and no segments

### ISSUE THREAD

**Issue by kendzi** [ppawel/osmonitor#29]
For road with no relation and no segments link "show in OSMonitor" don't work and give error: NoMethodError in BrowseController#road

eg. http://suncobalt.dyndns.org:8080/browse/road/PL/DW225

It should show empty page with refresh button.

**Comment by ppawel** [comment]
Thanks for the report, this is now fixed (although the map view does not show anything interesting :).

This bug was also the cause why reports have not been generated today.
