### ISSUE TITLE
Strange "last edited by ..." in some cases

### ISSUE THREAD

**Issue by SunCobalt** [ppawel/osmonitor#30]
last update: 2012-07-14 06:38:07 by Smolenski Nikola Smolenski (changeset 12213800)
The Link goes to
http://www.openstreetmap.org/user/Nikola

afaik the user has changed its OSM user name

**Comment by ppawel** [comment]
I can't find this example - which report is that? There was a problem with usernames that contain spaces but I fixed it yesterday.
