### ISSUE TITLE
Missing wikipedia links on administrative report

### ISSUE THREAD

**Issue by kendzi** [ppawel/osmonitor#32]
On administrative report there are no links to wikipednia. In Poland this can be used:

http://pl.wikipedia.org/wiki/Wojew%C3%B3dztwo_XXX
http://pl.wikipedia.org/wiki/Powiat_YYY

**Comment by ppawel** [comment]
Done.

**Comment by kendzi** [comment]
Maybe better place for link to wikipedia is column "Name"? Name it self can be a link.

**Comment by ppawel** [comment]
I agree, I will fix that.

**Comment by ppawel** [comment]
Done (again :-).
