### ISSUE TITLE
Display current report for a road in "road browser"

### ISSUE THREAD

**Issue by ppawel** [ppawel/osmonitor#8]
Now that OSMonitor has a proper frontend, it can display more information about a road. The tricky thing is the road input data (length) which is on the wiki.

**Comment by kendzi** [comment]
Show road status on map. All monitored road could be rendered on map. They could be rendered using color from monitor report. So it become easy to find „red” roads in neighborhood and fix them.

**Comment by ppawel** [comment]
That is a good idea but currently there are performance problems: generating a report for a long road (like DK1, DK3 or DK7) takes a lot of time (10-20 seconds) on the server that OSMonitor is running on.

I need to think about optimizations or maybe persisting the reports in the database (currently they are only stored on the wiki).

**Comment by ppawel** [comment]
BTW, on my laptop with SSD it takes less time than on the server - about 5 seconds for one of those long roads :-)

**Comment by ppawel** [comment]
This has been done 2-3 weeks ago but still need to work on some user-friendliess of the UI.
